version: '2'
services:
  riak:
    restart: always
    container_name: crypto-riak-node
    image: crypto/riak
    build: docker/riak
    ports:
      - "8087:8087"   # Protobuffer port
      - "8088:8088"   # Https port
      #- "8098:8098"   # Http port
      # Ports required for cluster
      - "4369:4369"
      - "8099:8099"
      - "6000-6005:6000-6005"
    env_file: .env
